"""Regenerates docs/SCENARIO_VALIDATION_REPORT.pdf from scenarios/significance_results.csv.

Interpretive "Reading" prose is never generated by this script -- it's read from
SCENARIO_READINGS below, which only gets edited after Claude drafts candidate text in
chat and the user approves it. Re-running this script after a data refresh never invents
new claims; it re-assembles whatever readings have already been signed off on, and warns
when a reading's underlying numbers have drifted since it was written (READING_BASIS).
"""

from __future__ import annotations

import os
import sys
import pandas as pd
from pathlib import Path

_PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _PROJECT_ROOT not in sys.path:
    sys.path.insert(0, _PROJECT_ROOT)
os.chdir(_PROJECT_ROOT)

from core.profiles import CAPABILITIES  # canonical order: restorativeness, nutrition, care

# ── Knobs ────────────────────────────────────────────────────────────────────
SIGNIFICANCE_CSV = Path("scenarios/significance_results.csv")
OUT_HTML = Path("docs/SCENARIO_VALIDATION_REPORT.html")
OUT_PDF = Path("docs/SCENARIO_VALIDATION_REPORT.pdf")
# How far a current median_diff may drift from a reading's recorded basis before that
# reading is flagged stale in the console output (absolute, on the [0,1] score scale).
STALENESS_TOLERANCE = 0.01

# ── Static methodology sections (1-4, 6) -- unchanged, transcribed verbatim ────
STATIC_SECTIONS_HTML = """
<h2>1. What is being compared, in general</h2>
<p>Every scenario compares two or more <b>conditions</b> — a baseline plus one or more
alternatives — over the same set of roughly 1,568 hexagonal cells covering the study area.</p>
<p>The <b>baseline</b> is the run made without changing anything: the universal-traveler
setup, full transit feed, full mode set, standard affordability — the same conditions the
model already runs with by default. It is not itself a "finding"; it's the reference point
every other condition in a scenario is measured against. Each <b>alternative condition</b>
changes exactly one thing (or a clearly-scoped bundle of things — see each scenario's own
description in Section 5) relative to that same baseline: a bus service removed, a
neighbourhood's POIs removed, a new transit line added, a different traveler profile
simulated. Whatever difference shows up between baseline and an alternative condition is
attributable to that specific change, precisely because everything else about the run is
held identical to baseline.</p>
<p>Each condition's capability score is computed independently for every hexagon, then the
results are lined up so that each hexagon has one score per condition, side by side.</p>

<h2>2. Choosing a capability score: discrete bands vs. a continuous score</h2>
<p>The model's production output places every hexagon into one of five ordered capability
bands (very low through very high) and reports the band's midpoint value. That is the right
choice for presenting results on a map, but it is a poor choice for detecting change
statistically: two hexagons that both remain in the "medium" band register as zero
difference even if one moved much closer to the boundary than the other, and the
significance test used here treats exact-zero differences as uninformative and discards
them. If most hexagons don't fully cross a band boundary, most of the sample ends up
contributing nothing to the test.</p>
<p>To avoid discarding real, sub-band movement, this analysis uses a continuous version of
the same underlying score instead: the smooth outranking credibility that the banding
procedure computes internally, before it collapses everything into five bands. It uses the
same concordance/discordance/veto logic as the production score, without the final rounding
step. It is not a different measure of accessibility, only a higher-resolution readout of
the same one. This continuous mode is opt-in. It never affects the model's normal
(production) output. Every result in this report was generated with it turned on.</p>

<h2>3. Baseline test: paired Wilcoxon signed-rank test</h2>
<p>For every (scenario, capability, condition) combination, the analysis:</p>
<ol>
<li>Keeps only hexagons that have valid data on both sides of the comparison.</li>
<li>Computes the paired difference in score between the two conditions, hexagon by
hexagon.</li>
<li>Runs a paired Wilcoxon signed-rank test on those differences. The null hypothesis is
that there is no systematic shift between the two conditions — i.e., that the paired
differences are symmetric around zero.</li>
<li>Estimates an effect size via a bootstrap 95% confidence interval on the
<b>median</b> difference (2,000 resamples).</li>
</ol>

<h2>4. Correction: spatial block sign-flip permutation test</h2>
<p>To account for the fact that nearby hexagons are not independent, a second,
spatially-aware test is run alongside the naive Wilcoxon test, following the block/cluster
permutation approach that is standard practice in spatial statistics and neuroimaging when
observations are geographically correlated:</p>
<ol>
<li><b>Group nearby hexagons into blocks.</b> Each hexagon is assigned to a roughly 500m
&times; 500m spatial cell based on its location; hexagons that land in the same cell form
one block. This block size is a tunable sensitivity parameter, not something fit to the
data — a sanity check is to confirm the resulting number of blocks is neither implausibly
small (over-correcting) nor close to the number of hexagons (no different from treating them
as independent).</li>
<li><b>Test statistic.</b> The same signed-rank information the Wilcoxon test uses is
combined into a single summary number for the whole comparison.</li>
<li><b>Permutation.</b> Many times over (thousands of repetitions), every hexagon in a
given block has its sign randomly and simultaneously flipped — never hexagon-by-hexagon —
and the test statistic is recomputed. This is the core of the correction: under this
resampling, correlated neighbours move together exactly as they would under a genuine,
spatially clustered effect, instead of having that correlation averaged away as if it
didn't exist.</li>
<li><b>Empirical significance.</b> The observed test statistic is compared against the
distribution of statistics produced by all those random permutations; the p-value is the
fraction of permutations that were as extreme or more extreme than what was actually
observed. Running more permutations lowers the smallest p-value the test can report (2,000
permutations bottoms out around 0.0005; 50,000 pushes that down to about 0.00002).</li>
<li><b>Correcting for testing many things at once.</b> Because this analysis runs many
such tests in a single report (three capabilities &times; several conditions per scenario),
a standard multiple-comparison correction (Benjamini-Hochberg) is applied across all of
them, for both the naive and the spatially-corrected p-values.</li>
</ol>
"""

METHODOLOGICAL_NOTES_HTML = """
<h2>6. Methodological notes for reproducibility</h2>
<ul>
<li>All results use the continuous capability score described in Section 2, not the
production five-band score.</li>
<li>The bootstrap confidence interval on the median difference uses 2,000 resamples at the
95% confidence level.</li>
<li>Multiple-comparison correction (Benjamini-Hochberg) is applied across all tests run
together in a given report.</li>
</ul>
"""

# ── Per-scenario static content (edited only via chat-reviewed drafts) ─────────
SCENARIO_READINGS: dict[str, dict] = {
    "public-strike": {
        "title": "5.1 Public transport strike",
        "what_changes": (
            "every bus route in the city is made effectively unusable — as if a citywide bus "
            "strike removed bus service entirely — while walking, biking, driving, the "
            "underlying transit schedule data, and affordability are left untouched. Any "
            "difference from baseline is therefore attributable to the loss of bus service "
            "alone, not to some other simultaneous change."
        ),
        "reading": [
            "care is the capability most exposed to losing bus service — nearly 70% of "
            "hexagons are affected, with a real (if modest) drop in the typical case. "
            "Restorativeness and nutrition show localized changes — some areas' parks or food "
            "access are partly bus-dependent — but no net citywide shift. The effect survives "
            "the spatial correction comfortably: this is a genuine, real finding rather than a "
            "statistical artifact."
        ],
        "reading_basis": {
            ("care", "baseline", "public_strike"): -0.010909,
            ("nutrition", "baseline", "public_strike"): 0.0,
            ("restorativeness", "baseline", "public_strike"): 0.0,
        },
    },
    "underservice-is-mirrionis": {
        "title": "5.2 Neighbourhood service loss (Is Mirrionis)",
        "what_changes": (
            "every POI that feeds any of the three capabilities and sits within the Is "
            "Mirrionis neighbourhood is removed from consideration entirely, as if that "
            "neighbourhood's local capability-feeding infrastructure — all of it, not one "
            "category — vanished. No routing, travel mode, speed, or transit-schedule change "
            "happens anywhere else in the city; only this one neighbourhood's set of POIs "
            "differs from baseline."
        ),
        "reading": [
            "care is again the most affected capability, both in size (−0.032, roughly three "
            "times the size of the bus-strike effect) and in reach (nearly every hexagon shows "
            "some change). Removing a neighbourhood's care-related POIs pulls down "
            "accessibility across a much larger surrounding area than the removal footprint "
            "itself, because nearby hexagons partly relied on that neighbourhood as one of "
            "several redundant options. Restorativeness and nutrition again show localized, "
            "net-zero-median effects. The finding is robust to the spatial correction."
        ],
        "reading_basis": {
            ("care", "baseline", "underservice_is_mirrionis"): -0.032475,
            ("nutrition", "baseline", "underservice_is_mirrionis"): 0.0,
            ("restorativeness", "baseline", "underservice_is_mirrionis"): 0.0,
        },
    },
    "new-metro": {
        "title": "5.3 New metro line",
        "what_changes": (
            "a new transit line is added to the network — an extension of the existing "
            "Metrocagliari line further into the city, with several new stops — while walking "
            "speed, affordability, and the set of enabled travel modes are all identical to "
            "baseline. The only difference from baseline is the presence and routing of this "
            "one additional line."
        ),
        "reading": [
            "this is the most spatially localized scenario by design — a single new corridor "
            "only affects a narrow band of hexagons (2.7%–28.5%, depending on capability), so "
            "the citywide median stays at zero for all three capabilities even though the "
            "effect within the corridor itself is real and consistently positive. The "
            "spatial-block test confirms that the localized effect is genuine."
        ],
        "reading_basis": {
            ("care", "baseline", "new_metro"): 0.0,
            ("nutrition", "baseline", "new_metro"): 0.0,
            ("restorativeness", "baseline", "new_metro"): 0.0,
        },
    },
    "elder-student": {
        "title": "5.4 Traveler profiles: student vs. elderly",
        "intro": (
            "This scenario compares three distinct traveler profiles, each simulated as a "
            "completely independent run (not a perturbation layered on baseline) — a "
            "universal baseline traveler, a low-income student, and an elderly traveler with "
            "mobility constraints:"
        ),
        "parameters": {
            "travel modes available": ("walk, bike, drive, bus", "walk, drive, bus (no bike)", "walk, bus only"),
            "walking speed": ("5 km/h", "5 km/h (same)", "2 km/h"),
            "affordability multiplier": ("1.0 (full)", "0.2 (low)", "0.5 (reduced)"),
            "free-canteen benefit": ("full", "full (same)", "none"),
            "transit accessibility": ("standard feed", "standard (same)", "wheelchair-accessible stops only"),
        },
        "what_changes": (
            "the student profile differs from baseline in exactly two respects — losing "
            "access to biking, and a much lower affordability multiplier — with speed, the "
            "canteen benefit, and transit accessibility unchanged. The elderly profile differs "
            "from baseline in every respect at once (modes, speed, affordability, canteen "
            "benefit, and transit accessibility all change together), so a baseline-vs-elderly "
            "difference can't be pinned on any single one of those changes. Only the "
            "student-vs-elderly comparison isolates the effect of speed, mode restriction, and "
            "transit accessibility with affordability held roughly comparable between the two "
            "(0.2 vs. 0.5, both low)."
        ),
        "reading": [
            "Baseline-vs-persona shifts are still real and consistently negative — every "
            "capability score drops for both personas relative to baseline — but much smaller "
            "than under the earlier flat-discount model (e.g. restorativeness "
            "baseline→student −0.946 → −0.332; care baseline→student −0.812 → −0.055). The "
            "reason is the same fix that produced this report: affordability now only "
            "discounts the 8 poi_types that are genuinely market/discretionary (organised "
            "sport, cinema/museums, dining, private wellness), leaving free/public services — "
            "parks, quiet spaces, groceries, public healthcare — untouched. Care is a clear "
            "illustration: none of its 5 services fall in the paid set, so its remaining "
            "−0.255 (baseline→elderly) / −0.055 (baseline→student) gap comes entirely from "
            "mobility differences (walking speed, mode restriction, accessible-stops-only "
            "transit for the elderly persona), not affordability at all. Restorativeness and "
            "nutrition, which do include paid services (sport/cultural activities, eating "
            "out), still show the largest drops, since those are the capabilities where the "
            "affordability discount actually has something to bite on.",
            "The student-to-elderly comparison changed direction on two of three "
            "capabilities: under the old flat-discount model elderly outranked student on "
            "care and restorativeness (the elderly persona's higher affordability multiplier, "
            "0.5 vs. 0.2, outweighed its mobility constraints); under the corrected model "
            "elderly now scores lower than student on all three capabilities (care −0.211, "
            "nutrition −0.125, restorativeness −0.203). With affordability's reach narrowed "
            "to genuinely paid services, the residual student-vs-elderly gap is increasingly "
            "explained by mobility and transit access — the student's higher walking speed "
            "and wider mode set now outweigh its slightly lower affordability (0.2 vs. 0.5) "
            "across the board. Unlike the previous version of this report, every one of the "
            "nine elder-student comparisons here survives the spatial correction robustly "
            "(p_block-perm at the permutation floor, 0.00002) — there is no longer a "
            "comparison whose apparent significance turns out to be noise once spatial "
            "correlation is accounted for.",
        ],
        "reading_basis": {
            ("care", "baseline", "elderly"): -0.255494,
            ("care", "baseline", "student"): -0.054934,
            ("care", "student", "elderly"): -0.210991,
            ("nutrition", "baseline", "elderly"): -0.625000,
            ("nutrition", "baseline", "student"): -0.514392,
            ("nutrition", "student", "elderly"): -0.125000,
            ("restorativeness", "baseline", "elderly"): -0.501922,
            ("restorativeness", "baseline", "student"): -0.331802,
            ("restorativeness", "student", "elderly"): -0.202681,
        },
    },
}


def _fmt_pct(x: float) -> str:
    return f"{x:.1f}%"


def _fmt_p(x: float) -> str:
    return "&lt; 0.0005" if x < 0.0005 else f"{x:.4f}"


def render_results_table(df: pd.DataFrame, scenario: str) -> str:
    """One row per (capability, comparison) for `scenario`, capabilities in CAPABILITIES
    order, comparisons in the order significance_analysis.R wrote them (already the
    baseline-first / multi-arm order the original report used). Uniform columns across
    every scenario -- a deliberate simplification vs. the original hand-authored report's
    per-scenario varying column set (e.g. new-metro dropped the CI column)."""
    sub = df[df["scenario"] == scenario]
    rows_html = []
    for capability in CAPABILITIES:
        for _, row in sub[sub["capability"] == capability].iterrows():
            rows_html.append(
                "<tr>"
                f"<td>{capability}</td>"
                f"<td>{row['group_a']} &rarr; {row['group_b']}</td>"
                f"<td>{int(row['n_hexagons'])}</td>"
                f"<td>{int(row['n_changed'])}</td>"
                f"<td>{_fmt_pct(row['pct_changed'])}</td>"
                f"<td>{row['median_diff']:+.3f}</td>"
                f"<td>[{row['ci_low']:+.3f}, {row['ci_high']:+.3f}]</td>"
                f"<td>{_fmt_p(row['p_value_block_perm'])}</td>"
                f"<td>{int(row['n_blocks'])}</td>"
                "</tr>"
            )
    return (
        "<table><thead><tr>"
        "<th>capability</th><th>comparison</th><th>n hex</th><th>n changed</th>"
        "<th>% changed</th><th>median &Delta;</th><th>95% CI</th>"
        "<th>p (block-perm)</th><th>n blocks</th>"
        "</tr></thead><tbody>" + "".join(rows_html) + "</tbody></table>"
    )


def render_parameters_table(parameters: dict[str, tuple[str, str, str]]) -> str:
    """elder-student's baseline/student/elderly persona-parameter table (Section 5.4 only)."""
    rows_html = "".join(
        f"<tr><td>{param}</td><td>{baseline}</td><td>{student}</td><td>{elderly}</td></tr>"
        for param, (baseline, student, elderly) in parameters.items()
    )
    return (
        "<table><thead><tr><th>parameter</th><th>baseline</th><th>student</th>"
        "<th>elderly</th></tr></thead><tbody>" + rows_html + "</tbody></table>"
    )


def load_significance_results(path: Path = SIGNIFICANCE_CSV) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(
            f"{path} not found -- run analysis/significance_analysis.R first "
            "(requires R; not available on this machine)."
        )
    return pd.read_csv(path)


def check_staleness(df: pd.DataFrame) -> bool:
    """Compare each reading's recorded reading_basis against the live CSV. Prints a warning
    per drifted/missing comparison. Returns True if anything is stale (or missing), so the
    caller can decide whether to still render the report or stop and ask for updated readings.
    """
    any_stale = False
    for scenario, entry in SCENARIO_READINGS.items():
        sub = df[df["scenario"] == scenario]
        for (capability, group_a, group_b), expected in entry.get("reading_basis", {}).items():
            row = sub[
                (sub["capability"] == capability)
                & (sub["group_a"] == group_a)
                & (sub["group_b"] == group_b)
            ]
            if row.empty:
                print(f"[stale] {scenario}/{capability}/{group_a}->{group_b}: "
                      f"no matching row in {SIGNIFICANCE_CSV} -- reading has no current data.")
                any_stale = True
                continue
            actual = float(row["median_diff"].iloc[0])
            if abs(actual - expected) > STALENESS_TOLERANCE:
                print(f"[stale] {scenario}/{capability}/{group_a}->{group_b}: "
                      f"reading written against median_diff={expected:g}, "
                      f"current value is {actual:g} (drift {abs(actual - expected):g} "
                      f"> tolerance {STALENESS_TOLERANCE:g}) -- reading needs review.")
                any_stale = True
    return any_stale


REPORT_CSS = """
body { font-family: "Liberation Serif", Georgia, serif; color: #1a1a1a; line-height: 1.4; }
h1 { text-align: center; }
h2 { margin-top: 2em; border-bottom: 1px solid #999; padding-bottom: 2px; }
h3 { margin-top: 1.5em; }
table { border-collapse: collapse; width: 100%; margin: 0.8em 0; font-size: 0.85em; }
th, td { border: 1px solid #999; padding: 4px 6px; text-align: left; }
th { background: #eee; }
li { margin-bottom: 0.4em; }
"""


def build_report_html(df: pd.DataFrame) -> str:
    scenario_blocks = []
    for scenario, entry in SCENARIO_READINGS.items():
        parts = [f"<h3>{entry['title']}</h3>"]
        if "intro" in entry:
            parts.append(f"<p>{entry['intro']}</p>")
            parts.append(render_parameters_table(entry["parameters"]))
        parts.append(f"<p><b>What changes vs. baseline</b>: {entry['what_changes']}</p>")
        parts.append(render_results_table(df, scenario))
        reading = entry["reading"]
        if len(reading) == 1:
            parts.append(f"<p><b>Reading</b>: {reading[0]}</p>")
        else:
            items = "".join(f"<li>{p}</li>" for p in reading)
            parts.append(f"<p><b>Reading</b> — multiple findings:</p><ol>{items}</ol>")
        scenario_blocks.append("\n".join(parts))

    return f"""<!doctype html>
<html><head><meta charset="utf-8"><title>Scenario Validation Report</title>
<style>{REPORT_CSS}</style></head>
<body>
<h1>Scenario Validation Report</h1>
<p>This report explains how each accessibility scenario is compared against baseline, what
statistical test establishes whether an observed difference is real and how to read the
results for each scenario. It documents the current hexagon-grid comparison and
significance-testing workflow.</p>
{STATIC_SECTIONS_HTML}
<h2>5. Per-scenario results</h2>
{"".join(scenario_blocks)}
{METHODOLOGICAL_NOTES_HTML}
</body></html>"""


def render_pdf(html: str, out_html: Path = OUT_HTML, out_pdf: Path = OUT_PDF) -> None:
    out_html.write_text(html, encoding="utf-8")
    print(f"[write] {out_html}")
    from weasyprint import HTML
    HTML(string=html, base_url=str(out_html.parent)).write_pdf(str(out_pdf))
    print(f"[write] {out_pdf}")


if __name__ == "__main__":
    df = load_significance_results()
    print(f"[load] {len(df)} rows from {SIGNIFICANCE_CSV}")
    print(df["scenario"].value_counts())
    stale = check_staleness(df)
    print("[staleness]", "some readings are stale -- see warnings above" if stale else "all readings match current data")
    html = build_report_html(df)
    render_pdf(html)
